import { expectType } from 'tsd'
import { ValidateQuery } from '../src/Validator'
import * as fixtures from './fixture'

expectType<ValidateQuery<fixtures.Q1, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q2, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q3, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q4, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q5, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q6, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q7, fixtures.DB>>(true)
// @ts-expect-error
expectType<ValidateQuery<fixtures.Q8, fixtures.DB>>(true) // FIXME
expectType<ValidateQuery<fixtures.Q9, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q10, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q11, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q12, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q13, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q14, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q15, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q16, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q17, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q18, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q19, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q20, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q21, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q22, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q23, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q24, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q25, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q26, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q28, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q29, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q30, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q31, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q32, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q33, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q34, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q35, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q36, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q37, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q38, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q39, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q200, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q201, fixtures.DB>>(true)
expectType<ValidateQuery<fixtures.Q202, fixtures.DB>>(true)



expectType<ValidateQuery<fixtures.NQ1, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ2, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ3, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ4, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ5, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ6, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ7, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ8, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ9, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ10, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ11, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ12, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ13, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ14, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ15, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ16, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ17, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ18, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ19, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ20, fixtures.DB>>(false)
// @ts-expect-error
expectType<ValidateQuery<fixtures.NQ21, fixtures.DB>>(false) // FIXME
expectType<ValidateQuery<fixtures.NQ22, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ23, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ24, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ25, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ26, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ27, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ200, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ201, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ202, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ203, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ204, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ205, fixtures.DB>>(false)
expectType<ValidateQuery<fixtures.NQ206, fixtures.DB>>(false)